[build]
  command   = "rm -rf .next .netlify && node src/netifly-environment.js && npm run build"
  publish   = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"