[build]
  command   = "node components/netifly-environment.js && npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[build.environment]
  NODE_VERSION = "18"

  [dev]
    functions = "out_functions"
    publish   = "out_publish"
    framework = "#static"